# Generated by Django 4.0.4 on 2022-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_completed',
            field=models.BooleanField(blank=b'I01\n', default=False, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery ', 'Cash On Delivery'), ('Khalti ', 'Khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
