# Generated by Django 4.0.4 on 2022-05-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_orders_payment_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
